# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

potential_part <- function(part, eval = NULL, mass = 1L, soft = 1, Munit = 1, Lunit = 1000, Vunit = 1) {
    .Call(`_celestial_potential_part`, part, eval, mass, soft, Munit, Lunit, Vunit)
}

